@Italia.Pdnd.IdentityModel.ClientAssertionGenerator.Api_HostAddress = http://localhost:5227

GET {{Italia.Pdnd.IdentityModel.ClientAssertionGenerator.Api_HostAddress}}/clientassertion/
Accept: application/json

###
